name: Latest blog post workflow
on:
  schedule: 
    - cron: '0 0 */20 * *' 
  workflow_dispatch: 

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Fetch tech blogs from medium
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          max_post_count: "5"
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          feed_list: 'https://medium.com/feed/@Aarsh'
