name: Latest blog post workflow
on:
  workflow_dispatch:
  schedule:
    - cron: '*/20 * * * *'
permissions:
  actions: write
jobs:
  update-readme-with-blog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          path: Aarsh2001
          persist-credentials: false
      
      - name: Update with latest blog
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          feed_list: 'https://medium.com/feed/@Aarsh'
