name: Latest blog post workflow
on:
  workflow_dispatch:
  schedule:
    - cron: '*/20 * * * *'
jobs:
  update-readme-with-blog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          path: Aarsh2001
      
      - name: Update with latest blog
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: 'https://medium.com/feed/@Aarsh'
